---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - keys/credentials.yaml
  - group_vars/vpc.yaml
  - group_vars/etcd_cluster.yaml
  - group_vars/coreos_cluster.yaml
  - group_vars/rds.yaml
  - group_vars/rabbitmq_cluster.yaml
  - group_vars/elasticsearch_cluster.yaml

  # clean everything in reverse (from main.yaml) order
  roles:
    # clean S3 resources
    - role: s3_config
    # clean VPC resources
    - role: vpc
