---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - group_vars/all

  tasks:

  # generate etcd key pair and store generated private key into file
  - name: Generate ec2 key
    ec2_key:
      region: "{{ ec2_region }}"
      name: "{{ etcd_instance_keypair }}"
    register: keypair
  # !!! Keep local file safe on your local machine only
  - name: write generated key to local file
    copy:
      dest: keys/"{{ etcd_key_file }}"
      content: "{{ keypair.key.private_key }}"
      mode: 0600
    when: keypair.changed
