# playbook to deploy all services
- include: detect_cluster.yaml

# allow executing ansible on coreos cluster members
- name: Bootstrap coreos cluster members with python
  hosts: coreos_cluster
  gather_facts: False
  roles:
    - role: defunctzombie.coreos-bootstrap

# add coreos-cluster vpc machines configuration here

# Note that CoreOS machines cannot be configured via ansible due to usage of auto scale groups
# machines started by amazon wouldn't be configured. But this mechanism can still be used for machines not using
# auto scale groups.
