---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - group_vars/all.yaml
  - group_vars/envs/{{ env | default("production") }}/vpc.yaml
  - group_vars/envs/{{ env | default("production") }}/etcd.yaml
  - group_vars/envs/{{ env | default("production") }}/nat.yaml
  - group_vars/envs/{{ env | default("production") }}/coreos.yaml

  roles:
    # generate etcd key pair
    - role: keygen
      keypair_region: "{{ ec2_region }}"
      keypair_name: "{{ etcd_keypair_name }}"
      keypair_file: "{{ etcd_keypair_file }}"
    # generate nat key pair
    - role: keygen
      keypair_region: "{{ ec2_region }}"
      keypair_name: "{{ nat_keypair_name }}"
      keypair_file: "{{ nat_keypair_file }}"
    # generate coreos key pair
    - role: keygen
      keypair_region: "{{ ec2_region }}"
      keypair_name: "{{ coreos_keypair_name }}"
      keypair_file: "{{ coreos_keypair_file }}"

    # create a new VPC
    - role: vpc
