# This playbook generates ssh_config for connecting from localhost to amazon
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - group_vars/ssh_config.yaml
  roles:
    - role: ssh_config_amazon
