---

- name: create security group for ELB
  ec2_group:
    name: "{{ elb_security_group.name }}"
    description: "{{ elb_security_group.desc }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ ec2_region }}"
    rules: "{{ elb_security_group.rules }}"
  register: elb_sg


- name: create ELB
  ec2_elb_lb:
    name: "{{ coreos_elb_name }}"
    state: present
    connection_draining_timeout: 60
    cross_az_load_balancing: "yes"
    region: "{{ ec2_region }}"
    security_group_ids: "{{ elb_sg.group_id }}"
    subnets: "{{ vpc_public_subnets }}"
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
      - protocol: http
        load_balancer_port: 88
        instance_port: 88
      - protocol: https
        load_balancer_port: 443
        instance_protocol: http
        instance_port: 80
        ssl_certificate_id: "{{ certificate_arn }}"
      - protocol: https
        load_balancer_port: 444
        instance_protocol: http
        instance_port: 88
        ssl_certificate_id: "{{ certificate_arn }}"
      - protocol: http
        load_balancer_port: 1936
        instance_port: 1936
      - protocol: http
        load_balancer_port: 8083
        instance_port: 8083
      - protocol: http
        load_balancer_port: 8086
        instance_port: 8086
    health_check:
      ping_protocol: http
      ping_port: 88
      ping_path: "/mgs/"
      response_timeout: 5
      interval: 10
      unhealthy_threshold: 4
      healthy_threshold: 5

- name: get ELB details
  local_action: command aws elb describe-load-balancers --load-balancer-names {{ coreos_elb_name }} --max-items 1 --output json
  register: elb_fact_out

- name: prepare ELB fact
  set_fact:
    elb_fact: "{{ elb_fact_out.stdout }}"

- name: obtain alias hosted zone id
  set_fact:
    id: "{{ hz_ids | get_hosted_zone_id() }}"

- name: create route53 subdomain for environment
  route53:
    command: create
    zone:  gaiahub.io
    record: "{{ dns }}.gaiahub.io"
    type: A
    alias: True
    overwrite: True
    alias_hosted_zone_id: "{{ id }}"
    value: "dualstack.{{ elb_fact.LoadBalancerDescriptions[0].CanonicalHostedZoneName }}"

- name: create route53 4th level domain for webhooks
  route53:
    command: create
    zone:  gaiahub.io
    record: "webhook.{{ dns }}.gaiahub.io"
    type: A
    alias: True
    overwrite: True
    alias_hosted_zone_id: "{{ id }}"
    value: "dualstack.{{ elb_fact.LoadBalancerDescriptions[0].CanonicalHostedZoneName }}"
