---
# find vpc id
- name: find bastion vpc
  ec2_vpc_net_facts:
    region: "{{ ec2_region }}"
    filters:
      cidr: "{{ vpc_cidr_block }}"
      tag:Name: gaia-vpc
  register: vpc_facts

- name: set vpc-id variable
  set_fact:
    vpc_id: "{{ vpc_facts.vpcs[0].id }}"
  when: vpc_facts.vpcs|length == 1


# discover hosted zone for VPC
- name: discover DNS zone (should be created by bastion playbooks)
  route53_facts:
    query: hosted_zone
    hosted_zone_method: list_by_name
    dns_name: "{{ vpc_dns_zone }}"
  register: dns_zone
