- name: create VPC peering to bastion vpc
  ec2_vpc_peer:
    name: "vpc-to-bastion-{{vpc_resource_tags.env}}"
    vpc_id: "{{ bastion_vpc_cidr_block }}"
    peer_vpc_id: "{{ vpc_id }}"
    region: "{{ ec2_region }}"
    state: present
    tags: "{{ vpc_peer_tags }}"
  register: vpc_peering_out

- name: get vpc peering id
  set_fact:
    vpc_peering_id: "{{ vpc_peering_out.results[0].id }}"

# create nat gateway
- name: allocate new elastic IP
  shell: "aws ec2 allocate-address --domain vpc"
  register: elastic_ip
- set_fact:
    elastic_ip_info: "{{ elastic_ip.stdout | from_json }}"

- name: create NAT Gateway service
  shell: "aws ec2 create-nat-gateway --subnet-id {{ ec2_vpc_out.subnets | get_subnets('tier', 'public') | first }} --allocation-id {{ elastic_ip_info.AllocationId }}"
  register: nat_gateway
- set_fact:
    nat_gateway_info: "{{ nat_gateway.stdout | from_json }}"

- name: wait until NAT gateway is available
  shell: "aws ec2 describe-nat-gateways --nat-gateway-ids {{ nat_gateway_info.NatGateway.NatGatewayId }} --filter Name=state,Values=available"
  register: nat_gateway
  until: nat_gateway.stdout.find( '{{ nat_gateway_info.NatGateway.NatGatewayId }}' ) > -1
  retries: 20
  delay: 5

- name: update vpc routing tables
  ec2_vpc:
    region: "{{ ec2_region }}"
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: "{{ vpc_resource_tags }}"
    internet_gateway: "{{ vpc_internet_gateway|string }}"
    subnets: "{{ ec2_vpc_out.subnets }}"
    route_tables:
      - subnets: "{{ ec2_vpc_out.subnets | get_subnets('tier', 'public', 'cidr') }}"
        routes:
          - dest: 0.0.0.0/0
            gw: igw
          - dest: "{{ bastion_vpc_cidr_block }}"
            gw: "{{ vpc_peering_id }}"
        resource_tags: "{{ vpc_route_tables_tags }}"
      - subnets: "{{ ec2_vpc_out.subnets | get_subnets('tier', 'private', 'cidr') }}"
        routes:
          - dest: 0.0.0.0/0
            gw: "{{ nat_gateway_info.NatGateway.NatGatewayId }}"
          - dest: "{{ bastion_vpc_cidr_block }}"
            gw: "{{ vpc_peering_id }}"
        resource_tags: "{{ vpc_route_tables_tags }}"
  register: ec2_vpc_out

- name: get bastion vpc route table
  ec2_vpc_route_table_facts:
    region: "{{ ec2_region }}"
    filters:
      tag:Name: "{{ bastion_vpc_rt_name }}"
      tag:env: "{{ environ }}"
  register: bastion_rts

- name: update bastion route tables
  local_action: command aws ec2 create-route --route-table-id {{ item.id }} --destination-cidr-block {{ vpc_cidr_block }} --vpc-peering-connection-id {{ vpc_peering_id }}
  with_items: "{{ bastion_rts.route_tables }}"
  ignore_errors: true
