---

# generate application security keys for further usage by Dex - should be in environment
- name: generate dex admin api key
  shell: "dd if=/dev/random bs=1 count=128 2>/dev/null | base64 | tr -d '\n'"
  register: dex_admin_key_out
- set_fact:
    DEX_API_SECRET: "{{ dex_admin_key_out.stdout }}"
- name: generate dex secret key
  shell: "dd if=/dev/random bs=1 count=32 2>/dev/null | base64 | tr -d '\n'"
  register: dex_secret_key_out
- set_fact:
    DEX_SECRET: "{{ dex_secret_key_out.stdout }}"
- debug: var="{{ DEX_API_SECRET }}"
- debug: var="{{ DEX_SECRET }}"
