# coreos - parameters
coreos_keypair_name: coreos-keypair-test
coreos_keypair_file: coreos-key-test.pem

# choose either: alpha, beta or stable channel
# (!) currently using "alpha" since flannel 0.5.0 (with AWS backend support) available only on alpha
coreos_channel: alpha

coreos_cluster_size: 4
coreos_max_cluster_size: 16
coreos_health_check_period: 60

coreos_flannel_cidr_block: 192.168.0.0/16

# note: for flannel use manually create role with required pilicies
#       https://coreos.com/flannel/docs/latest/vpc-backend.html
#       https://coreos.com/blog/introducing-flannel-0.5.0-with-aws-and-gce/
coreos_instance_profile: flannel-role

coreos_asg_name: coreos-asg-test

coreos_lc_name: coreos-lc-test

coreos_instance_type: m3.xlarge     # 4 vCPU, 15GB RAM, 2x40 SSD

coreos_instance_tags:
  - Name: coreos
    group: gaia
    type: cluster_node
    env: testing
    decription: CoreOS HA Cluster Node

coreos_security_group:
  name: coreos_sg_test
  desc: the security group for CoreOS cluster
  rules:
    - proto: tcp
      from_port: 2379
      to_port: 2379
      group_name: coreos_sg_test
    - proto: tcp
      from_port: 2380
      to_port: 2380
      group_name: coreos_sg_test
    - proto: tcp
      from_port: 4001
      to_port: 4001
      group_name: coreos_sg_test
    - proto: tcp
      from_port: 7001
      to_port: 7001
      group_name: coreos_sg_test
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: "{{ bastion_vpc_cidr_block }}"

# https server certificate
gaia_ca_file: gaia-ca-test
