# create new VPC
- name: create a new VPC
  ec2_vpc:
    region: "{{ ec2_region }}"
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: "{{ vpc_resource_tags }}"
    internet_gateway: "{{ vpc_internet_gateway|string }}"
    subnets: "{{ vpc_subnets }}"
    wait: true
  register: ec2_vpc_out

# discover hosted zone for VPC
- name: discover DNS zone
  route53_facts:
    query: hosted_zone
    hosted_zone_method: list_by_name
    dns_name: "{{ vpc_dns_zone }}"
  register: dns_zone
# Fail if DNS hosted zone does not exist for VPC
- name: Check DNS zone existence
  fail:
    msg: "Expected DNS zone was not found"
  when: "{{ dns_zone.HostedZones | length }} == 0"

# associate VPC with Bastion DNS zone
- name: associate VPC with Bastion DNS zone
  route53_zone:
    vpc_id: "{{ ec2_vpc_out.vpc_id }}"
    vpc_region: "{{ ec2_region }}"
    zone: "{{ dns_zone.HostedZones[0].Name }}"
    state: present

# get VPC facts: id, private and public subnets
- name: get VPC facts
  set_fact:
    vpc_id: "{{ ec2_vpc_out.vpc_id }}"
    vpc_private_subnets: "{{ ec2_vpc_out.subnets | get_subnets('tier', 'private') }}"
    vpc_public_subnets: "{{ ec2_vpc_out.subnets | get_subnets('tier', 'public') }}"
