- name: create a new vpc
  ec2_vpc:
    region: "{{ ec2_region }}"
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: "{{ vpc_resource_tags }}"
    internet_gateway: "{{ vpc_internet_gateway|string }}"
    subnets: "{{ vpc_subnets }}"
    wait: true
  register: ec2_vpc_out

- name: get vpc id
  set_fact:
    vpc_id: "{{ ec2_vpc_out.vpc_id }}"

- name: get vpc private subnets
  set_fact:
    vpc_private_subnets: "{{ ec2_vpc_out.subnets | get_subnets('tier', 'private') }}"

- name: get vpc public subnets
  set_fact:
    vpc_public_subnets: "{{ ec2_vpc_out.subnets | get_subnets('tier', 'public') }}"
