# coreos - parameters
coreos_keypair_name: coreos-prod-keypair
coreos_keypair_file: coreos-prod-key.pem

coreos_channel: stable
coreos_cluster_size: 4
coreos_max_cluster_size: 16
coreos_health_check_period: 60

coreos_flannel_cidr_block: 10.20.0.0/16

# note: for flannel use manually create role with required pilicies
#       https://coreos.com/flannel/docs/latest/vpc-backend.html
coreos_instance_profile: flannel-role

coreos_asg_name: coreos-asg-prod

coreos_lc_name: coreos-lc-prod

coreos_instance_type: m3.xlarge     # 4 vCPU, 15GB RAM, 2x40 SSD

coreos_instance_tags:
  - Name: coreos
    group: gaia
    type: cluster_node
    env: production
    decription: CoreOS HA Cluster Node

coreos_security_group:
  name: coreos_sg_prod
  desc: the security group for CoreOS cluster
  rules:
    - proto: tcp
      from_port: 2379
      to_port: 2379
      group_name: coreos_sg_prod
    - proto: tcp
      from_port: 2380
      to_port: 2380
      group_name: coreos_sg_prod
