# etcd - common instance parameters
etcd_keypair_name: etcd-keypair-prod
etcd_keypair_file: etcd-key-prod.pem
etcd_channel: stable
etcd_cluster_size: 3
etcd_max_cluster_size: 9
etcd_health_check_period: 60
etcd_asg_name: etcd-asg-prod
etcd_lc_name: etcd-lc-prod

etcd_instance_type: r3.large      # Memory optimized 15GB RAM

etcd_block_device_mappings:
  - DeviceName: /dev/xvda
    Ebs:
      VolumeSize: 10
      VolumeType: "gp2"
      DeleteOnTermination: true

etcd_instance_tags:
  - Name: etcd
    group: gaia
    type: cluster_node
    env: production
    decription: etcd HA Cluster Node

etcd_security_group:
  name: etcd_sg_prod
  desc: the security group for etcd cluster
  rules:
    - proto: tcp
      from_port: 2379
      to_port: 2379
      cidr_ip: "{{ vpc_cidr_block }}"
    - proto: tcp
      from_port: 2380
      to_port: 2380
      cidr_ip: "{{ vpc_cidr_block }}"
    - proto: tcp
      from_port: 4001
      to_port: 4001
      cidr_ip: "{{ vpc_cidr_block }}"
    - proto: tcp
      from_port: 7001
      to_port: 7001
      cidr_ip: "{{ vpc_cidr_block }}"
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: "{{ bastion_vpc_cidr_block }}"
