# delete result_upload volume
- debug: msg="Working on volume {{ volume_name }} ..."

- name: "Find volume"
  shell: "aws ec2 describe-volumes --filter 'Name=tag:Name,Values={{ volume_name }}' --output json"
  register: volume_out
- set_fact:
    volume_info: "{{ volume_out.stdout | from_json }}"

- name: "Check we found no more than 1 volume"
  fail:
    msg: "Expected no more than 1 {{ volume_name }} volumes, found {{ volume_info.Volumes | length }}"
  when: "{{ volume_info.Volumes | length }} > 1"

- name: "Detach volume (forced)"
  shell: "aws ec2 detach-volume --volume-id {{ volume_info.Volumes[0].VolumeId }} --force"
  when: "{{ volume_info | has_volume_state('in-use') }}"

- name: "Wait until volume is detached"
  shell: "aws ec2 describe-volumes --filter 'Name=tag:Name,Values={{ volume_name }}' --output json"
  when: "{{ volume_info | has_volume_state('in-use') }}"
  register: volume_out
  until: "{{ volume_out  }}  and 'available' in {{ volume_out.stdout }}"
  delay: 10
  retries: 5

- name: "Delete volume"
  ec2_vol:
    id: "{{ volume_info.Volumes[0].VolumeId }}"
    region: "{{ ec2_region }}"
    state: absent
  when: "{{ volume_info.Volumes | length }} == 1"
